export const STORAGE_KEYS = {
  FAVORITES: "casino-favorites",
  TOKEN: "token",
  USER: "user-data",
} as const;

export const ANIMATION_DURATION = {
  SHORT: 200,
  MEDIUM: 300,
  LONG: 500,
} as const;

export const TOAST_DURATION = 3000;
export const LOADING_DELAY = 1000;

export const BDT_SYMBOL = "৳";

export const TRANSLATIONS = {
  BN: {
    HOME: "হোম",
    PROMOTIONS: "প্রমোশন",
    WINNERS: "বিজয়ীদের তালিকা",
    VIP: "ভিআইপি",
    REFERRAL: "রেফার বোনাস",
    DOWNLOAD: "ডাউনলোড",
    CONTACT: "যোগাযোগ করুন",
    SOCIAL_MEDIA: "সোশ্যাল মিডিয়া",
    LOGIN: "লগ ইন",
    SIGNUP: "সাইন আপ",
    LOGOUT: "লগ আউট",
    BALANCE: "ব্যালেন্স",
    GAMES: "গেমস",
    FAVORITES: "পছন্দসই",
    SEARCH_PLACEHOLDER: "গেম বা প্রোভাইডার খুঁজুন...",
    NO_GAMES_FOUND: "কোন গেম পাওয়া যায়নি",
    RESET_FILTERS: "ফিল্টার মুছে ফেলুন",
    LOADING: "লোড হচ্ছে...",
    SHOW_MORE: "আরো দেখুন",
    PLAY_NOW: "এখন খেলুন",
    BY: "কর্তৃক",
    PREMIUM: "প্রিমিয়াম",
    HOT_GAMES: "গরম খেলা",
    CASINO: "ক্যাসিনো",
    SLOTS: "স্লট",
    TABLE: "টেবিল",
    CRASH: "ক্রাশ",
    FISHING: "ফিসিং",
    ALL_GAMES: "সব গেম",
    RESPONSIBLE_GAMING: "দায়িত্বশীল গেম্বলিং",
    COPYRIGHT: "সর্বস্বত্ব সংরক্ষিত।",
    BEST_QUALITY: "Best Quality Platform for iGaming",
    ABOUT_US: "আমাদের সম্পর্কে",
    TERMS: "শর্তাবলী",
    PRIVACY: "গোপনীয়তা নীতি",
    FAQ: "FAQ",
    PAYMENT_PARTNERS: "পেমেন্ট পার্টনার",
    
    // Messages / labels
    SEARCH_INPUT_ARIA: "গেম বা প্রোভাইডার অনুসন্ধান করুন",
    CLEAR_SEARCH_ARIA: "অনুসন্ধান মুছুন",
    PLAY_GAME_ARIA: "{gameName} খেলুন",
    ADD_FAVORITE_ARIA: "পছন্দসইতে যোগ করুন",
    REMOVE_FAVORITE_ARIA: "পছন্দসই থেকে সরান",
    CLEAR_FILTERS_ARIA: "সব ফিল্টার মুছুন",
    GAME_GRID_ARIA: "গেম গ্রিড",
    FILTER_CONTROLS_ARIA: "গেম ফিল্টার কন্ট্রোল",
    
    // Footer / headers
    PREMIUM_GAMING_EXCELLENCE: "২০২৬ সালে ক্রিকেট বেটিংয়ের জন্য পিবিসি৮৮ ক্যাসিনো সেরা পছন্দ। আমাদের গেমগুলি এবং বিভাগগুলি চমৎকার সেবা প্রদান করে।",
    EST: "প্রতিষ্ঠিত.",
    PLAY_RESPONSIBLY: "দায়িত্বশীল গেম্বলিং",
    PLAY_RESPONSIBLY_DETAILS: "গেম খেলা বিনোদন এবং মজার জন্য হওয়া উচিত। আপনি যদি মনে করেন আপনার জুয়ার সমস্যা হতে পারে, অনুগ্রহ করে অবিলম্বে পেশাদার সাহায্য নিন।",
    OVER18_ONLY: "১৮+ শুধুমাত্র",
    LICENSED_REGULATED: "লাইসেন্সপ্রাপ্ত এবং নিয়ন্ত্রিত",
    SECURE_GAMING: "নিরাপদ গেমিং",
    ROYAL_CASINO_CRAFTED: "২০২৬ পিবিসি৮৮ ক্যাসিনো - পিবিসি৮৮ স্পোর্টস বেটিং লবি।",
    PREMIUM_GAMING_EXPERIENCE: "অত্যাধুনিক প্রযুক্তি দ্বারা চালিত প্রিমিয়াম গেমিং অভিজ্ঞতা",
    
    // Game card/grid
    NEW: "নতুন",
    HOT: "গরম",
    PLAY: "খেলুন",
    GAMES_FOUND: "{count} টি গেম পাওয়া গেছে",
    SHOW_ALL: "সব দেখান",
    ROYAL_CASINO: "পিবিসি৮৮ ক্যাসিনো",
    PREMIUM_GAMING_DESTINATION: "সেরা ক্রিকেট বেটিং এবং ক্যাসিনো লবি",
    VIP_MEMBER: "ভিআইপি মেম্বার",
    SOMETHING_WENT_WRONG: "ওহ! কিছু ভুল হয়েছে",
    SOMETHING_UNEXPECTED_HAPPENED: "আমরা দুঃখিত, কিন্তু একটি অপ্রত্যাশিত সমস্যা ঘটেছে।",
    RELOAD_PAGE: "পেজ রিলোড করুন",
    FILTER_GAMES: "গেম ফিল্টার",
    FAVORITES_ONLY: "শুধুমাত্র পছন্দসই",
    CLEAR_ALL: "সব মুছুন",
    CASH_BALANCE: "ক্যাশ ব্যালেন্স",
    NOTICE: "বিজ্ঞপ্তি",
    AVAILABLE: "টি পাওয়া গেছে",
    NO_GAMES_MESSAGE: "দুঃখিত, আপনার অনুসন্ধান অনুযায়ী কোন ফলাফল পাওয়া যায়নি। অন্য কিছু চেষ্টা করুন।",
    PLAY_SUCCESS: "🎮 {gameName} শুরু হচ্ছে! শুভকামনা!",
    FAVORITE_ADDED: "{gameName} পছন্দসইতে যোগ করা হয়েছে!",
    FAVORITE_REMOVED: "{gameName} পছন্দসই থেকে সরানো হয়েছে!",
    OUT_OF_FIVE_STARS: "৫ স্টারের মধ্যে",
    SPORTS: "স্পোর্টস",
    CARDS: "কার্ড গেমস",
    MEGAWAYS: "মেগাওয়েজ",
    LOTTERY: "লটারী",
    ARCADE: "আর্কেড",
    DEPOSIT: "ডিপোজিট",
    RNG_CERTIFIED: "আরএনজি সার্টিফাইড",
    SECURE: "এবং নিরাপদ",
    FOLLOW_US: "আমাদের অনুসরণ করুন",
    PARTNERS: "অংশীদার",
    PAYMENT_METHODS: "মুল্য পরিশোধ পদ্ধতি",
    LOBBY_CARD_VIP_CASHBACK: "ভিআইপি ক্যাশব্যাক",
    LOBBY_CARD_VIP_DESC: "৫ বিটিসি পর্যন্ত ২০০% ম্যাচ ও ১০০ ফ্রি স্পিন",
    LOBBY_CARD_RAFFLE: "সাপ্তাহিক ক্রিপ্টো র্যাফেল",
    LOBBY_CARD_RAFFLE_DESC: "দৈনিক ও সাপ্তাহিক ক্রিপ্টো র্যাফেল পান",
    LOBBY_CARD_TOURNAMENT: "হাই রোলার টুর্নামেন্ট",
    LOBBY_CARD_TOURNAMENT_DESC: "হাই রোলারদের জন্য বিশেষ অফার",
    LEADERBOARD_RANK: "র্যাংক",
    LEADERBOARD_PLAYER: "খেলোয়াড়",
    LEADERBOARD_GAME: "খেলা",
    LEADERBOARD_WIN: "জয়ের পরিমাণ",
    DEPOSIT_METHOD: "পেমেন্ট পদ্ধতি নির্বাচন করুন",
    DEPOSIT_AMOUNT: "জমার পরিমাণ প্রবেশ করুন",
    DEPOSIT_SUBMIT: "জমার অনুরোধ জমা দিন",
    DEPOSIT_SUCCESS: "জমার অনুরোধ সফলভাবে তৈরি হয়েছে! এডমিন অনুমোদনের পর ব্যালেন্স যুক্ত হবে।",
    LIVE: "লাইভ ক্যাসিনো",
    COMPANY: "কোম্পানি",
    BLOG_NEWS: "ব্লগ ও খবর",
    CAREERS: "ক্যারিয়ার",
    LIVE_SUPPORT: "২৪/৭ লাইভ সাপোর্ট",
    SECURITY_CENTER: "নিরাপত্তা কেন্দ্র",
    HERO_TITLE: "অত্যাধুনিক ক্রিকেট বেটিং এবং প্রিমিয়াম ক্যাসিনো লবি",
  },
  EN: {
    HOME: "Home",
    PROMOTIONS: "Promotions",
    WINNERS: "Winners List",
    VIP: "VIP",
    REFERRAL: "Referral Bonus",
    DOWNLOAD: "Download",
    CONTACT: "Contact Us",
    SOCIAL_MEDIA: "Social Media",
    LOGIN: "Login",
    SIGNUP: "Sign Up",
    LOGOUT: "Logout",
    BALANCE: "Balance",
    GAMES: "Games",
    FAVORITES: "Favorites",
    SEARCH_PLACEHOLDER: "Find games or providers...",
    NO_GAMES_FOUND: "No games found",
    RESET_FILTERS: "Clear Filters",
    LOADING: "Loading...",
    SHOW_MORE: "Show More",
    PLAY_NOW: "Play Now",
    BY: "by",
    PREMIUM: "Premium",
    HOT_GAMES: "Hot Games",
    CASINO: "Casino",
    SLOTS: "Slots",
    TABLE: "Table",
    CRASH: "Crash",
    FISHING: "Fishing",
    ALL_GAMES: "All Games",
    RESPONSIBLE_GAMING: "Responsible Gaming",
    COPYRIGHT: "All rights reserved.",
    BEST_QUALITY: "Best Quality Platform for iGaming",
    ABOUT_US: "About Us",
    TERMS: "Terms",
    PRIVACY: "Privacy Policy",
    FAQ: "FAQ",
    PAYMENT_PARTNERS: "Payment Partners",
    
    // Messages / labels
    SEARCH_INPUT_ARIA: "Search games or providers",
    CLEAR_SEARCH_ARIA: "Clear search",
    PLAY_GAME_ARIA: "Play {gameName}",
    ADD_FAVORITE_ARIA: "Add to favorites",
    REMOVE_FAVORITE_ARIA: "Remove from favorites",
    CLEAR_FILTERS_ARIA: "Clear all filters",
    GAME_GRID_ARIA: "Game grid",
    FILTER_CONTROLS_ARIA: "Game filter controls",
    
    // Footer / headers
    PREMIUM_GAMING_EXCELLENCE: "PBC88 Casino is the best choice for cricket betting in 2026. Our games and sections offer excellent services.",
    EST: "Est.",
    PLAY_RESPONSIBLY: "Play Responsibly",
    PLAY_RESPONSIBLY_DETAILS: "Gaming should be for entertainment and fun. If you think you might have a gambling problem, please seek professional help immediately.",
    OVER18_ONLY: "18+ Only",
    LICENSED_REGULATED: "Licensed & Regulated",
    SECURE_GAMING: "Secure Gaming",
    ROYAL_CASINO_CRAFTED: "2026 PBC88 Casino - PBC88 Sports Betting Lobby.",
    PREMIUM_GAMING_EXPERIENCE: "Premium gaming experience powered by state-of-the-art technology",
    
    // Game card/grid
    NEW: "New",
    HOT: "Hot",
    PLAY: "Play",
    GAMES_FOUND: "{count} games found",
    SHOW_ALL: "Show All",
    ROYAL_CASINO: "PBC88 Casino",
    PREMIUM_GAMING_DESTINATION: "Best cricket betting and casino lobby",
    VIP_MEMBER: "VIP Member",
    SOMETHING_WENT_WRONG: "Oh! Something went wrong",
    SOMETHING_UNEXPECTED_HAPPENED: "We are sorry, but an unexpected issue occurred.",
    RELOAD_PAGE: "Reload Page",
    FILTER_GAMES: "Filter Games",
    FAVORITES_ONLY: "Favorites Only",
    CLEAR_ALL: "Clear All",
    CASH_BALANCE: "Cash Balance",
    NOTICE: "Notice",
    AVAILABLE: "Available",
    NO_GAMES_MESSAGE: "Sorry, no results found for your search. Try something else.",
    PLAY_SUCCESS: "🎮 Starting {gameName}! Good luck!",
    FAVORITE_ADDED: "{gameName} added to favorites!",
    FAVORITE_REMOVED: "{gameName} removed from favorites!",
    OUT_OF_FIVE_STARS: "out of 5 stars",
    SPORTS: "Sports",
    CARDS: "Card Games",
    MEGAWAYS: "Megaways",
    LOTTERY: "Lottery",
    ARCADE: "Arcade",
    DEPOSIT: "Deposit",
    RNG_CERTIFIED: "RNG Certified",
    SECURE: "& Secure",
    FOLLOW_US: "Follow Us",
    PARTNERS: "Partners",
    PAYMENT_METHODS: "Payment Methods",
    LOBBY_CARD_VIP_CASHBACK: "VIP Cashback",
    LOBBY_CARD_VIP_DESC: "200% Match up to 5 BTC & 100 free spins",
    LOBBY_CARD_RAFFLE: "Weekly Crypto Raffle",
    LOBBY_CARD_RAFFLE_DESC: "Get the daily weekly crypto raffle",
    LOBBY_CARD_TOURNAMENT: "High Roller Tournament",
    LOBBY_CARD_TOURNAMENT_DESC: "Offers for high roller tournament",
    LEADERBOARD_RANK: "Rank",
    LEADERBOARD_PLAYER: "Player",
    LEADERBOARD_GAME: "Game",
    LEADERBOARD_WIN: "Win Amount",
    DEPOSIT_METHOD: "Select Payment Method",
    DEPOSIT_AMOUNT: "Enter Deposit Amount",
    DEPOSIT_SUBMIT: "Submit Deposit Request",
    DEPOSIT_SUCCESS: "Deposit request created successfully! It will reflect in your balance upon admin approval.",
    LIVE: "Live Casino",
    COMPANY: "Company",
    BLOG_NEWS: "Blog & News",
    CAREERS: "Careers",
    LIVE_SUPPORT: "24/7 Live Support",
    SECURITY_CENTER: "Security Center",
    HERO_TITLE: "THE ULTIMATE CRYPTO CASINO EXPERIENCE",
  }
} as const;

// Legacy constants mapping to BN for backwards compatibility
export const BANGLA_TEXT = TRANSLATIONS.BN;
export const PLACEHOLDER_MESSAGES = {
  SEARCH: BANGLA_TEXT.SEARCH_PLACEHOLDER,
  NO_GAMES: BANGLA_TEXT.NO_GAMES_MESSAGE,
  LOADING: BANGLA_TEXT.LOADING,
  PLAY_SUCCESS: BANGLA_TEXT.PLAY_SUCCESS,
  FAVORITE_ADDED: BANGLA_TEXT.FAVORITE_ADDED,
  FAVORITE_REMOVED: BANGLA_TEXT.FAVORITE_REMOVED,
  PREMIUM_CASINO_GAMES: BANGLA_TEXT.PREMIUM_GAMING_DESTINATION,
  NO_GAMES_FOUND: BANGLA_TEXT.NO_GAMES_FOUND,
  RESET_FILTERS: BANGLA_TEXT.RESET_FILTERS,
} as const;

export const ARIA_LABELS = {
  SEARCH_INPUT: TRANSLATIONS.BN.SEARCH_INPUT_ARIA,
  CLEAR_SEARCH: TRANSLATIONS.BN.CLEAR_SEARCH_ARIA,
  PLAY_GAME: TRANSLATIONS.BN.PLAY_GAME_ARIA,
  ADD_FAVORITE: TRANSLATIONS.BN.ADD_FAVORITE_ARIA,
  REMOVE_FAVORITE: TRANSLATIONS.BN.REMOVE_FAVORITE_ARIA,
  CLEAR_FILTERS: TRANSLATIONS.BN.CLEAR_FILTERS_ARIA,
  GAME_GRID: TRANSLATIONS.BN.GAME_GRID_ARIA,
  FILTER_CONTROLS: TRANSLATIONS.BN.FILTER_CONTROLS_ARIA,
} as const;

export const FOOTER_MAIN_MESSAGES = {
  PREMIUM_GAMING_EXCELLENCE: TRANSLATIONS.BN.PREMIUM_GAMING_EXCELLENCE,
  EST: TRANSLATIONS.BN.EST,
};

export const FOOTER_BOTTOM_MESSAGES = {
  PLAY_RESPONSIBLY: TRANSLATIONS.BN.PLAY_RESPONSIBLY,
  PLAY_RESPONSIBLY_DETAILS: TRANSLATIONS.BN.PLAY_RESPONSIBLY_DETAILS,
  OVER18_ONLY: TRANSLATIONS.BN.OVER18_ONLY,
  LICENSED_REGULATED: TRANSLATIONS.BN.LICENSED_REGULATED,
  SECURE_GAMING: TRANSLATIONS.BN.SECURE_GAMING,
  ROYAL_CASINO_CRAFTED: TRANSLATIONS.BN.ROYAL_CASINO_CRAFTED,
  PREMIUM_GAMING_EXPERIENCE: TRANSLATIONS.BN.PREMIUM_GAMING_EXPERIENCE,
};

export const GAME_CARD_HEADER = {
  NEW: TRANSLATIONS.BN.NEW,
  HOT: TRANSLATIONS.BN.HOT,
  PLAY: TRANSLATIONS.BN.PLAY,
};

export const GAME_GRID_MESSAGES = {
  SHOWING_GAMES: TRANSLATIONS.BN.GAMES_FOUND,
  SHOW_ALL_GAMES: TRANSLATIONS.BN.SHOW_ALL,
};

export const HEADER_MESSAGES = {
  ROYAL_CASINO: TRANSLATIONS.BN.ROYAL_CASINO,
  PREMIUM_GAMING_DESTINATION: TRANSLATIONS.BN.PREMIUM_GAMING_DESTINATION,
  GAMES: TRANSLATIONS.BN.GAMES,
  FAVORITES: TRANSLATIONS.BN.FAVORITES,
  VIP_MEMBER: TRANSLATIONS.BN.VIP_MEMBER,
};

export const ERROR_BOUNDARY_MESSAGES = {
  SOMETHING_WENT_WRONG: TRANSLATIONS.BN.SOMETHING_WENT_WRONG,
  SOMETHING_UNEXPECTED_HAPPENED: TRANSLATIONS.BN.SOMETHING_UNEXPECTED_HAPPENED,
  RELOAD_PAGE: TRANSLATIONS.BN.RELOAD_PAGE,
};

export const FILTER_CONTROLS = {
  FILTER_GAMES: TRANSLATIONS.BN.FILTER_GAMES,
  FAVORITES_ONLY: TRANSLATIONS.BN.FAVORITES_ONLY,
  CLEAR_ALL: TRANSLATIONS.BN.CLEAR_ALL,
};

export const GAME_CARD_CONTEXT = {
  BY: TRANSLATIONS.BN.BY,
  PREMIUM: TRANSLATIONS.BN.PREMIUM,
  PLAY_NOW: TRANSLATIONS.BN.PLAY_NOW,
  OUT_OF_FIVE_STARS: TRANSLATIONS.BN.OUT_OF_FIVE_STARS,
};
